version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

defaults: &defaults
  parameters:
    node_version:
      type: string
      default: ""

commands:
  npmrc:
    steps:
      - run:
          name: Create .npmrc
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

  setup_git:
    steps:
      - run:
          name: "Setup git environment"
          command: git config --global core.autocrlf false

  install_node_npm:
    <<: *defaults
    description: Install specific version of Node
    steps:
      - run:
          name: Installing node version << parameters.node_version >>
          command: nvm install << parameters.node_version >>
      - run:
          name: Using node version << parameters.node_version >>
          command: nvm use << parameters.node_version >>

  show_node_npm_version:
    description: Log Node and npm version
    steps:
      - run:
          name: Node version
          command: node --version
      - run:
          name: NPM version
          command: npm --version

  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: Install npm dependencies
          command: npm install
jobs:
  security-scans:
    resource_class: small
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - show_node_npm_version
      - install_deps
      - prodsec/security_scans:
          mode: auto
          release-branch: master
          open-source-additional-arguments: --exclude=test
          iac-scan: disabled

  lint:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - show_node_npm_version
      - install_deps
      - run:
          name: Run lint
          command: npm run lint

  test-unix:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - show_node_npm_version
      - install_deps
      - run:
          name: Run tests
          command: npm run test:unit

  release:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    resource_class: small
    steps:
      - checkout
      - install_deps
      - run:
          name: Release
          command: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: os-team-managed-alerts
          filters:
            branches:
              ignore:
                - master

      - security-scans:
          name: Security Scans
          node_version: "12"
          context:
            - open_source-managed
            - nodejs-install

      - lint:
          name: lint
          context: nodejs-install
          node_version: "12"

      # UNIX tests
      - test-unix:
          name: Unix Tests for Node << matrix.node_version >>
          context: nodejs-install
          requires:
            - lint
          matrix:
            parameters:
              node_version: ["16.13.1", "14.18.2", "12.22.7"]

      - release:
          name: Release
          context: nodejs-lib-release
          node_version: "lts"
          requires:
            - lint
            - test-unix
          filters:
            branches:
              only:
                - master
